
name: Release
on: workflow_dispatch
permissions: write-all


jobs:
  Telegram:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Compile
      run: gcc  getdents.c -o getdents
    - name: Compile2
      run: gcc  getdents2.c -o getdents-fullpath
    - name: Compile3
      run: gcc  getdents-quotepath.c -o getdents-quotepath
    - name: ls
      run: ls
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: getdents binary
        automatic_release_tag: all
        prerelease: false
        files: |
          getdents
          getdents-fullpath
          getdents-quotepath
        repo_token: ${{ secrets.GITHUB_TOKEN }}

